### ISSUE TITLE
Error send if you don't post at least 2 "facts"

### ISSUE THREAD

**Issue by soupist** [EvotecIT/PSDiscord#1]
Everything is working as expected, other than it requires 2 "$Fact" to be sent. You can use the same fact, but if I don't send 2, it errors out.

**Comment by PrzemyslawKlys** [comment]
```
Install-Module PSDiscord -Force
```

Please run this. It should work. Discord REST requires Array of Hashtables and if there's one element there's no array. I had to force Array creation.
