### ISSUE TITLE
Special characters/unicode chars not supported

### ISSUE THREAD

**Issue by DamianRyse** [EvotecIT/PSDiscord#4]
It seems that special characters and unicode chars such as Emotes are not supported. When I send a String to a Discord Webhook URL which contains special characters, they'are being converted to questionmarks.

**Comment by PrzemyslawKlys** [comment]
I believe you can change this line:

https://github.com/EvotecIT/PSDiscord/blob/807ad63a64bcf5ec01022eb05f715973f75ee4d3/Public/Send-DiscordMessage.ps1#L51 

To:

```powershell
Invoke-RestMethod -Uri $WebHookUrl -Body $Body -Method Post -ContentType 'application/json; charset=UTF-8'  -Verbose:$false
```

You can edit the PSM1 file in your installed modules - it would be line 508. Remember to `Import-Module PSDiscord -Force` after change.

![image](https://user-images.githubusercontent.com/15063294/120276989-bcf46580-c2b3-11eb-8e10-e52bc8d1ddce.png)

To fix it. Give it a go and let me know if it works?

**Comment by DamianRyse** [comment]
It worked like a charm! Thank you!

**Comment by PrzemyslawKlys** [comment]
I still need to  fix this in code here :) Or you can make a PR
